version: "3.8"

services:
  redis:
    image: 'redis:alpine'
    container_name: celery-json-redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
    volumes:
      - ./redis_data:/data
    ports:
      - '6379:6379'

  worker:
    image: celery-json
    volumes:
      - .:/app
    depends_on:
      - redis
      - scheduler
    env_file:
      - .env
    entrypoint: [ './entrypoint.sh', 'worker', 'default' ]


  scheduler:
    build: .
    image: celery-json
    container_name: celery-json-scheduler
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - instance=scheduler
    env_file:
      - .env
    entrypoint: ['./entrypoint.sh', 'scheduler']
